version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     networks:
      - traefik-public
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       APP_NAME: ${APP_NAME}

      deploy:
        labels:
          traefik.http.services.${APP_NAME}.loadbalancer.server.port: '80'

          traefik.http.routers.${APP_NAME}-https.rule: Host(`${APP_NAME}.scrapp.app`)
          traefik.http.routers.${APP_NAME}-https.entrypoints: https
          traefik.http.routers.${APP_NAME}-https.tls.certresolver: le
          traefik.http.routers.${APP_NAME}-https.tls: 'true'

          traefik.constraint-label: traefik-public
          traefik.http.routers.${APP_NAME}-http.rule: Host(`${APP_NAME}.scrapp.app`)
          traefik.docker.network: traefik-public
          traefik.enable: 'true'
          traefik.http.routers.${APP_NAME}-http.middlewares: https-redirect
          traefik.http.routers.${APP_NAME}-http.entrypoints: http

volumes:
    db_data:

networks:
  traefik-public:
    external: true